# Generated by Django 4.2.6 on 2023-10-18 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dispositivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modelo", models.CharField(max_length=100)),
                ("num_serie", models.CharField(max_length=100)),
                ("imei", models.CharField(blank=True, max_length=100, null=True)),
                ("observacion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Estado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("codigo", models.CharField(max_length=100)),
                ("contacto", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Software",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=100)),
                ("cantidad_licencias", models.IntegerField(default=0)),
                (
                    "duracion",
                    models.CharField(
                        choices=[
                            ("0", "Permantente"),
                            ("1", "Un Año"),
                            ("2", "Dos años"),
                            ("3", "Tres años"),
                        ],
                        default=1,
                        max_length=50,
                    ),
                ),
                ("fecha_registro", models.DateField(auto_now=True)),
                ("fecha_compra", models.DateField()),
                ("fecha_caducidad", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="TipoDispositivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Inventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("valor", models.FloatField()),
                (
                    "numero_orden",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("H", "Harware"), ("S", "Software")], max_length=20
                    ),
                ),
                ("disponible", models.BooleanField(default=False)),
                ("archivo", models.ImageField(upload_to="datos/")),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.estado",
                    ),
                ),
                (
                    "hadrware",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.dispositivo",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.proveedor",
                    ),
                ),
                (
                    "software",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.software",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dispositivo",
            name="estado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventario.estado"
            ),
        ),
        migrations.AddField(
            model_name="dispositivo",
            name="marca",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventario.marca"
            ),
        ),
        migrations.AddField(
            model_name="dispositivo",
            name="proveedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventario.proveedor"
            ),
        ),
        migrations.AddField(
            model_name="dispositivo",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventario.tipodispositivo",
            ),
        ),
    ]
