# Generated by Django 4.2.6 on 2023-10-27 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='software',
            name='factura',
        ),
        migrations.AddField(
            model_name='inventario',
            name='factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.factura'),
        ),
    ]
