# Generated by Django 4.2.6 on 2023-10-24 03:13

from django.db import migrations, models
import django.db.models.deletion
import inventario.models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inventario',
            name='persona_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.persona'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='num_serie',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='marca',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='inventario.marca'),
        ),
    ]
