# Generated by Django 4.2.6 on 2023-11-26 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='fecha_caducidad',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='fecha_compra',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='software',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='software',
            name='fecha_compra',
        ),
        migrations.RemoveField(
            model_name='software',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='software',
            name='nombre',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='imagenDispostivo',
            field=models.ImageField(null=True, upload_to='datos/dispositivos/'),
        ),
        migrations.AddField(
            model_name='factura',
            name='dateTimeOfUpload',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedor'),
        ),
        migrations.AddField(
            model_name='factura',
            name='uploadedFile',
            field=models.FileField(null=True, upload_to='facturas/'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='duracion',
            field=models.CharField(choices=[('0', 'Permanente'), ('1', 'Un Año'), ('2', 'Dos años'), ('3', 'Tres años'), ('4', 'Cuatro años')], default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='inventario',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='fecha_registro',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.proveedor'),
        ),
        migrations.AlterField(
            model_name='software',
            name='marca',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='software', to='inventario.marca'),
        ),
    ]
