# Generated by Django 4.2.6 on 2023-10-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="software",
            name="fecha_caducidad",
            field=models.DateField(null=True),
        ),
    ]
