# Generated by Django 4.2.6 on 2023-12-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_inventario_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='observación'),
        ),
    ]
