# Generated by Django 4.2.6 on 2023-10-24 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventario', '0002_inventario_content_type_inventario_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.marca'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
