# Generated by Django 4.2.6 on 2023-11-26 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_dispositivo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='tipo',
            field=models.ForeignKey(help_text='Tipo dispositivo', on_delete=django.db.models.deletion.CASCADE, to='inventario.tipodispositivo'),
        ),
    ]
