# Generated by Django 4.2.6 on 2023-10-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_alter_software_fecha_caducidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="software",
            name="duracion",
            field=models.CharField(
                choices=[
                    ("0", "Permantente"),
                    ("1", "Un Año"),
                    ("2", "Dos años"),
                    ("3", "Tres años"),
                ],
                default="1",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="software",
            name="fecha_compra",
            field=models.DateField(null=True),
        ),
    ]
