# Generated by Django 4.2.6 on 2023-10-31 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_inventario_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='fecha_caducidad',
        ),
    ]
