# Generated by Django 4.2.6 on 2023-10-24 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_dispositivo_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.marca'),
        ),
    ]
