# Generated by Django 4.2.6 on 2023-11-26 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_dispositivo_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='tipo',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='tipo_dispositivo',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='inventario.tipodispositivo'),
            preserve_default=False,
        ),
    ]
