# Generated by Django 4.2.6 on 2023-10-18 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0004_alter_software_fecha_caducidad_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventario",
            name="archivo",
            field=models.ImageField(null=True, upload_to="datos/"),
        ),
        migrations.AlterField(
            model_name="inventario",
            name="proveedor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventario.proveedor",
            ),
        ),
    ]
