# Generated by Django 4.2.6 on 2023-11-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_software_fecha_caducidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
