# Generated by Django 4.2.6 on 2023-11-26 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_dispositivo_tipo_dispositivo_tipo_dispositivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispositivo',
            old_name='tipo_dispositivo',
            new_name='tipo',
        ),
    ]
