# Generated by Django 4.2.6 on 2023-11-03 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_inventario_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.proveedor'),
        ),
        migrations.AlterField(
            model_name='software',
            name='marca',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='software', to='inventario.marca'),
        ),
    ]
