# Generated by Django 4.2.6 on 2023-11-26 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_rename_tipo_dispositivo_dispositivo_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispositivo',
            old_name='tipo',
            new_name='tipo_dispositivo',
        ),
    ]
