# Generated by Django 4.2.6 on 2023-10-18 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0005_alter_inventario_archivo_alter_inventario_proveedor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventario",
            name="archivo",
        ),
    ]
