# Generated by Django 4.2.6 on 2023-11-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_rename_tipo_dispositivo_tipo_dispositivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodispositivo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
