# Generated by Django 4.2.6 on 2023-11-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_estado_estado_alter_marca_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
