# Generated by Django 4.2.6 on 2023-11-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_rename_fecha_caducidad_inventario_fecha_caducidad_dispositivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='fecha_caducidad_dispositivo',
            new_name='fecha_caducidad',
        ),
    ]
