# Generated by Django 4.2.6 on 2023-11-26 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_rename_fecha_caducidad_dispositivo_inventario_fecha_caducidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispositivo',
            old_name='imagenDispostivo',
            new_name='imagen_dispostivo',
        ),
    ]
