# Generated by Django 4.2.6 on 2023-11-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_remove_dispositivo_imagen_dispostivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='imagen_dispostivo',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='imagen_dispostivo',
            field=models.ImageField(null=True, upload_to='datos/dispositivos/'),
        ),
    ]
