# Generated by Django 4.2.6 on 2023-11-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_alter_dispositivo_imagen_dispositivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='imagen_dispositivo',
            field=models.ImageField(null=True, upload_to='datos/dispositivos/', verbose_name='Foto Dispositivo'),
        ),
    ]
