# Generated by Django 4.2.6 on 2023-11-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_alter_dispositivo_imagen_dispositivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='dateTimeOfUpload',
            new_name='fecha_registro',
        ),
        migrations.RenameField(
            model_name='inventario',
            old_name='fecha_compra',
            new_name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='software',
            name='cantidad_licencias',
        ),
        migrations.AddField(
            model_name='factura',
            name='cantidad_licencias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='factura',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_factura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='orden_de_compra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='cuenta_asociada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='fecha_instalacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de instalación'),
        ),
    ]
