# Generated by Django 4.2.6 on 2023-11-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_rename_datetimeofupload_factura_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='uploadedFile',
            field=models.FileField(blank=True, null=True, upload_to='facturas/'),
        ),
    ]
