# Generated by Django 4.2.6 on 2023-11-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_alter_factura_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='numero_orden',
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_registro',
            field=models.DateField(auto_now=True),
        ),
    ]
