# Generated by Django 4.2.6 on 2023-12-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_remove_inventario_numero_orden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='imagen_dispositivo',
            field=models.ImageField(blank=True, null=True, upload_to='datos/dispositivos/', verbose_name='Foto Dispositivo'),
        ),
    ]
