# Generated by Django 4.2.6 on 2023-12-05 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_alter_dispositivo_imagen_dispositivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='proveedor',
        ),
        migrations.AlterField(
            model_name='factura',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.proveedor'),
        ),
    ]
