# Generated by Django 4.2.6 on 2023-12-07 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_remove_inventario_proveedor_alter_factura_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='uploadedFile',
            new_name='facturapdf',
        ),
    ]
