# Generated by Django 4.2.6 on 2023-12-08 07:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_alter_persona_gerencia'),
        ('inventario', '0023_rename_uploadedfile_factura_facturapdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='persona_asignada',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='persona_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.persona'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_factura',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
