# Generated by Django 4.2.6 on 2023-12-09 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_remove_inventario_persona_asignada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='marca',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='inventario.marca'),
        ),
    ]
