# Generated by Django 4.2.6 on 2023-12-10 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0025_alter_software_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='fecha_modificacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cantidad_licencias',
            field=models.IntegerField(default=1),
        ),
    ]
