# Generated by Django 4.2.6 on 2023-12-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0026_inventario_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='cantidad_licencias',
        ),
        migrations.AddField(
            model_name='software',
            name='cantidad_disponibles',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='software',
            name='cantidad_licencias',
            field=models.IntegerField(default=1),
        ),
    ]
