# Generated by Django 4.2.6 on 2023-12-14 20:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('personas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoLic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicenciaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignada', models.DateField(verbose_name='Fecha de asignación')),
                ('observacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now=True, verbose_name='Fecha de registro')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas_asignadas', to='personas.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la licencia')),
                ('numero_identificacion', models.CharField(max_length=100, unique=True, verbose_name='Número de identificación')),
                ('fecha_activacion', models.DateField(auto_now_add=True, verbose_name='Fecha de activación')),
                ('fecha_vencimiento', models.DateField(default=datetime.date(2024, 12, 13), editable=False, verbose_name='Fecha de vencimiento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('asignada', models.BooleanField(default=False)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='licencias.estadolic', verbose_name='Estado de la licencia')),
                ('licenciaUsuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licencia_asignada', to='licencias.licenciausuario')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='inventario.software')),
                ('tipo_licencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencias.tipolicencia', verbose_name='Tipo de licencia')),
            ],
        ),
    ]
