# Generated by Django 4.2.6 on 2023-12-08 07:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0003_alter_persona_gerencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0024_remove_inventario_persona_asignada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoLic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_identificacion', models.CharField(max_length=100, verbose_name='Número de identificación')),
                ('fecha_activacion', models.DateField()),
                ('fecha_vencimiento', models.DateField(default=datetime.date(2024, 12, 7), editable=False)),
                ('completado', models.BooleanField(default=False, editable=False)),
                ('observacion', models.TextField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencias.estadolic')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='inventario.factura')),
            ],
        ),
        migrations.CreateModel(
            name='TipoLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicenciaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignada', models.DateField()),
                ('observacion', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('licencias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencias.licencia')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.persona')),
                ('usuario_asigna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='licencia',
            name='personasAsig',
            field=models.ManyToManyField(through='licencias.LicenciaUsuario', to='personas.persona'),
        ),
        migrations.AddField(
            model_name='licencia',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='inventario.software'),
        ),
        migrations.AddField(
            model_name='licencia',
            name='tipo_licencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencias.tipolicencia'),
        ),
    ]
