# Generated by Django 4.2.6 on 2023-12-14 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencia',
            name='asignada',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='licenciaUsuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licencia_asignada', to='licencias.licenciausuario'),
        ),
    ]
