# Generated by Django 4.2.6 on 2023-12-09 01:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_alter_persona_gerencia'),
        ('inventario', '0024_remove_inventario_persona_asignada_and_more'),
        ('licencias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenciausuario',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='licenciausuario',
            name='person',
        ),
        migrations.AddField(
            model_name='licenciausuario',
            name='fecha_registro',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='licenciausuario',
            name='persona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='personas.persona'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='licencia',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='licencias.estadolic', verbose_name='Estado de la licencia'),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='inventario.factura'),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='fecha_activacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de activación'),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date(2024, 12, 7), editable=False, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la licencia'),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='observacion',
            field=models.TextField(verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='personasAsig',
            field=models.ManyToManyField(related_name='licencias_asignadas', through='licencias.LicenciaUsuario', to='personas.persona'),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='tipo_licencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencias.tipolicencia', verbose_name='Tipo de licencia'),
        ),
        migrations.AlterField(
            model_name='licenciausuario',
            name='fecha_asignada',
            field=models.DateField(verbose_name='Fecha de asignación'),
        ),
        migrations.AlterField(
            model_name='licenciausuario',
            name='licencias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='licencias.licencia'),
        ),
        migrations.AlterField(
            model_name='licenciausuario',
            name='observacion',
            field=models.CharField(max_length=100, verbose_name='Observación'),
        ),
    ]
