# Generated by Django 4.2.6 on 2023-12-09 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_alter_persona_gerencia'),
        ('licencias', '0002_remove_licenciausuario_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciausuario',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.persona'),
        ),
    ]
