# Generated by Django 4.2.6 on 2023-12-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0002_alter_licencia_asignada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencia',
            name='asignada',
            field=models.BooleanField(default=False),
        ),
    ]
