# Generated by Django 4.2.6 on 2023-12-09 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('licencias', '0003_alter_licenciausuario_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciausuario',
            name='usuario_asigna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
