# Generated by Django 4.2.6 on 2023-12-14 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0003_alter_licencia_asignada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licencia',
            name='licenciaUsuario',
        ),
        migrations.AddField(
            model_name='licenciausuario',
            name='licenciaUsuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licencia_asignada', to='licencias.licencia'),
        ),
        migrations.AddConstraint(
            model_name='licenciausuario',
            constraint=models.UniqueConstraint(fields=('persona', 'licenciaUsuario'), name='LicenciaUnica'),
        ),
    ]
