# Generated by Django 4.2.6 on 2023-12-09 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_alter_persona_gerencia'),
        ('licencias', '0004_alter_licenciausuario_usuario_asigna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencia',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date(2024, 12, 8), editable=False, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='licenciausuario',
            name='observacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observación'),
        ),
        migrations.AlterUniqueTogether(
            name='licenciausuario',
            unique_together={('persona', 'licencias')},
        ),
    ]
