# Generated by Django 4.2.6 on 2023-12-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0004_remove_licencia_licenciausuario_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='licenciausuario',
            name='LicenciaUnica',
        ),
        migrations.AddConstraint(
            model_name='licenciausuario',
            constraint=models.UniqueConstraint(fields=('persona', 'licenciaUsuario'), name='LicenciaUnica'),
        ),
    ]
