# Generated by Django 4.2.6 on 2023-12-14 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0005_remove_licenciausuario_licenciaunica_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licenciausuario',
            old_name='licenciaUsuario',
            new_name='licencia',
        ),
    ]
