# Generated by Django 4.2.6 on 2023-12-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0005_remove_licenciausuario_licenciaunica_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='licenciausuario',
            name='LicenciaUnica',
        ),
        migrations.RenameField(
            model_name='licenciausuario',
            old_name='licenciaUsuario',
            new_name='licencia',
        ),
        migrations.AddConstraint(
            model_name='licenciausuario',
            constraint=models.UniqueConstraint(fields=('persona', 'licencia'), name='LicenciaUnica'),
        ),
    ]
