# Generated by Django 4.2.6 on 2023-12-09 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0006_rename_licencias_licenciausuario_licencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licencia',
            name='factura',
        ),
    ]
