# Generated by Django 4.2.6 on 2023-12-09 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_alter_persona_gerencia'),
        ('licencias', '0007_remove_licencia_factura'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='licenciausuario',
            name='unique licencia',
        ),
        migrations.AlterField(
            model_name='licenciausuario',
            name='licencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='licencias.licencia', unique=True),
        ),
        migrations.AlterField(
            model_name='licenciausuario',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='personas.persona'),
        ),
        migrations.AddConstraint(
            model_name='licenciausuario',
            constraint=models.UniqueConstraint(fields=('persona', 'licencia'), name='LicenciaUnica'),
        ),
    ]
