# Generated by Django 4.2.6 on 2023-12-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0007_alter_licencia_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciausuario',
            name='observacion',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Observaciones'),
        ),
    ]
