# Generated by Django 4.2.6 on 2023-12-18 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0006_rename_licenciausuario_licenciausuario_licencia'),
        ('licencias', '0008_alter_licenciausuario_observacion'),
    ]

    operations = [
    ]
