# Generated by Django 4.2.6 on 2023-12-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0008_remove_licenciausuario_unique_licencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencia',
            name='numero_identificacion',
            field=models.CharField(max_length=100, unique=True, verbose_name='Número de identificación'),
        ),
    ]
