# Generated by Django 4.2.6 on 2023-12-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0009_alter_licencia_numero_identificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licenciausuario',
            old_name='usuario_asigna',
            new_name='creado_por',
        ),
    ]
