# Generated by Django 4.2.6 on 2023-12-18 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0009_merge_20231218_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencia',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date(2024, 12, 17), editable=False, verbose_name='Fecha de vencimiento'),
        ),
    ]
