# Generated by Django 4.2.6 on 2023-12-10 04:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0010_rename_usuario_asigna_licenciausuario_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencia',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date(2024, 12, 9), editable=False, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='licenciausuario',
            name='licencia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='licencias.licencia'),
        ),
    ]
