# Generated by Django 4.2.6 on 2023-12-24 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0010_alter_licencia_fecha_vencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licencia',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='licencia',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date(2024, 12, 23), editable=False, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='licenciausuario',
            name='observacion',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Observación'),
        ),
    ]
