# Generated by Django 4.2.6 on 2023-12-11 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0011_alter_licencia_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencia',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date(2024, 12, 10), editable=False, verbose_name='Fecha de vencimiento'),
        ),
    ]
