# Generated by Django 4.2.6 on 2023-12-29 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0011_remove_licencia_observaciones_licencia_observacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencia',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date(2024, 12, 28), editable=False, verbose_name='Fecha de vencimiento'),
        ),
    ]
