# Generated by Django 4.2.6 on 2023-12-11 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_alter_persona_gerencia'),
        ('licencias', '0012_alter_licencia_fecha_vencimiento'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='licenciausuario',
        #     name='persona',
        # ),
        migrations.AddField(
            model_name='licenciausuario',
            name='personas',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='personas_asignados', to='personas.persona'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='licenciausuario',
            name='licencia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='licencia_asignada', to='licencias.licencia'),
        ),
    ]
