# Generated by Django 4.2.6 on 2023-12-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0013_remove_licenciausuario_persona_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='licenciausuario',
            name='LicenciaUnica',
        ),
        migrations.AddConstraint(
            model_name='licenciausuario',
            constraint=models.UniqueConstraint(fields=('personas', 'licencia'), name='LicenciaUnica'),
        ),
    ]
