# Generated by Django 4.2.6 on 2023-12-11 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0014_remove_licenciausuario_licenciaunica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenciausuario',
            name='persona',
        ),
    ]
