# Generated by Django 4.2.6 on 2023-12-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0015_remove_licenciausuario_persona'),
    ]

    operations = [
      
        migrations.RemoveField(
            model_name='licencia',
            name='observacion',
        ),
        migrations.AddField(
            model_name='licencia',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observacines'),
        ),
    ]
