# Generated by Django 4.2.6 on 2023-12-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0017_remove_licencia_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licencia',
            name='personasAsig',
        ),
        migrations.AlterField(
            model_name='licencia',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
