# Generated by Django 4.2.6 on 2023-12-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0018_remove_licencia_personasasig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencia',
            name='asignada',
            field=models.BooleanField(default=False),
        ),
    ]
