# Generated by Django 4.2.6 on 2023-12-12 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('licencias', '0019_licencia_asignada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciausuario',
            name='creado_por',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='creado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
