# Generated by Django 4.2.6 on 2023-12-12 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0021_alter_licenciausuario_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencia',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date(2024, 12, 11), editable=False, verbose_name='Fecha de vencimiento'),
        ),
    ]
