# Generated by Django 4.2.6 on 2023-10-10 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Personas',
        ),
    ]
