# Generated by Django 4.2.6 on 2023-10-11 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_rename_usuario_personas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personas',
            options={'verbose_name_plural': 'Personas'},
        ),
    ]
